### PR TITLE
cpu.x86: fix silly bug in %clear

### PR DESCRIPTION
**Pull request by bjourne**
Simple bug in %clear must have caused the crashes.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Merged, thanks!

**Comment by mrjbq7** [comment]
How should I resolve this ``help-lint`` warning?

```
==== resource:basis/compiler/cfg/stacks/clearing/clearing-docs.factor

resource:basis/compiler/cfg/stacks/clearing/clearing-docs.factor: 19

Asset: T{ link f dangerous-insn? }

Assertion failed
got    "vacant-peek\ninsn T{ ##peek f f R 0 f }"
expect "f"
```

Thanks,

**Comment by bjourne** [comment]
Ops! The second line 

`{ { 0 { } } { 2 { 0 1 } } } T{ ##peek { loc R 0 } } dangerous-insn? .` should be 
`{ { 0 { } } { 2 { } } } T{ ##peek { loc R 0 } } dangerous-insn? .`

I can make a patch for it.

**Comment by mrjbq7** [comment]
No worries, I can fix !

**Pull request closed without merging**
