### PR TITLE
locals.parser.tests: fixes the unit tests

### PR DESCRIPTION
**Pull request by bjourne**
Trivial fix to make the unit tests run here.

### CODE REVIEW

**Comment by mrjbq7** [comment]
I removed those because I thought they "shouldn't be necessary". And tests pass if you run them yourself but as part of load-all test-all it fails.  I suppose it's bad form to leave a broken build but was hoping to identify what caused the failure. 

Maybe we merge this and then investigate separately?

**Comment by bjourne** [comment]
Oh, sorry I totally misunderstood you then. But you're right it is a little strange that those weird `<<` and `>>` are needed there.

**Comment by mrjbq7** [comment]
Seems like ``manifest`` is being set to ``f`` or unset somehow.

This reproduces the test failures:

```factor
f manifest [ "locals" test ] with-variable
```

**Comment by mrjbq7** [comment]
Closing for now I forgot about this and applied the fix but didn't give you credit, whoops.

**Pull request closed without merging**
