### PR TITLE
Doc fixes for upstream

### PR DESCRIPTION
**Pull request by AlexIljin**
These are only the documentation changes, but I also took the liberty to rename some variables in some stack effect declarations, purely for better readability and consistency.

### CODE REVIEW

**Comment by mrjbq7** [comment]
I'm not sure about the vector stack effect change since ``u`` and ``v`` are frequently used for vectors.

See, for example:

https://en.wikipedia.org/wiki/Vector_notation#Operations

**Comment by AlexIljin** [comment]
OK, but the word is v+n, not u+n. See what I mean?

**Comment by mrjbq7** [comment]
Well, I think the desire was to have the same first arg whether it had 1-arity or 2-arity, so if you follow that:

```
: vadd ( v w -- x )
: v+n ( v n -- x )
```

But generally, most math seems to use ``u + v`` or ``u * v`` for operations... ?

**Comment by mrjbq7** [comment]
Cherrypicked the first three commits.  @erg can weigh in on the math.vectors change?

**Comment by AlexIljin** [comment]
Yes, and I only changed things for consistency so that in vneg, vnot, vsqrt etc. you actually see the "v" parameter. Same for v^n, v/n, and so on. Purely a cosmetic fix.

**Comment by AlexIljin** [comment]
u+v and such are left intact.

**Comment by mrjbq7** [comment]
ahh, gotcha.  @erg?

**Comment by mrjbq7** [comment]
P.S. thanks for the contributions!!!

**Comment by AlexIljin** [comment]
Happy to help!

**Comment by AlexIljin** [comment]
It seems that @erg has left the building : ))

**Comment by erg** [comment]
Ha. I'm here, I forgot to reply!

Last patch seems fine!

**Comment by mrjbq7** [comment]
Okay, pulled the last commit, thanks @AlexIljin!

**Pull request closed without merging**
