### PR TITLE
Fix 1345 part2

### PR DESCRIPTION
**Pull request by bjourne**
I think I found the cause of the `project-euler.044` compilation problem. But the committs in this pr should fix it.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Merged, thanks!

**Comment by mrjbq7** [comment]
I see this on linux-32 and mac-32:

```
=== benchmark.bootstrap1
vocab:bootstrap/assembler/x86.32.windows.factor

36: << "vocab:bootstrap/assembler/x86.32.factor" parse-file suffix! >> call
                                                                      ^
No suitable arithmetic method
left    f
right   0
generic -
```

**Comment by bjourne** [comment]
Hm is it something random? The benchmarks works for me when I run them.

**Comment by erg** [comment]
Looks like a duplicate of #1329.

Somewhere in the compiler is ``get``ing a variable that is f instead of a number?

**Comment by mrjbq7** [comment]
Saw this on mac32:

```
==== math.transforms.bwt:

resource:extra/math/transforms/bwt/bwt.factor

3: USING: accessors assocs fry kernel locals sequences
4: sequences.rotated sorting ;
                    ^
No suitable arithmetic method
left    f
right   2
generic -


==== sequences.rotated:

No suitable arithmetic method
left    f
right   2
generic -
```

**Pull request merged**
