### PR TITLE
Windows fixes part2

### PR DESCRIPTION
**Pull request by bjourne**
The sampling profiling tests failed on my new windows machine. It appears to have been caused by a funny difference in how vs2015 and vs2014 and earlier compiles 64bit code. The committs below should fix it.

### CODE REVIEW

**Comment by mrjbq7** [comment]
That sounds great, but does this now prevent successful compiling with vs2014, or just add compatibility with vs2015?

**Comment by erg** [comment]
I've been trying to bootstrap on a Rackspace instance. Win64 works fine, win32 crashes on bootstrap. The fault code is a c++ exception:

```
Fetching latest boot image...
Bootstrapping...
*** Stage 2 early init... done
Loading resource:basis/bootstrap/stage2.factor
Loading resource:basis/command-line/command-line.factor
Loading resource:basis/fry/fry.factor
Loading resource:basis/locals/backend/backend.factor
Loading resource:basis/windows/windows.factor
Loading resource:basis/alien/libraries/libraries.factor
Loading resource:basis/compiler/errors/errors.factor
Loading resource:basis/summary/summary.factor
Loading resource:basis/alien/libraries/windows/windows.factor
Loading resource:basis/windows/errors/errors.factor
Loading resource:basis/alien/data/data.factor
Loading resource:basis/alien/arrays/arrays.factor
Loading resource:basis/alien/c-types/c-types.factor
Loading resource:basis/cpu/architecture/architecture.factor
Loading resource:basis/delegate/delegate.factor
Loading resource:basis/locals/locals.factor
Loading resource:basis/macros/macros.factor

Copying fresh factor.image to factor.image.fresh.
The system cannot find the file specified.
Build failed.
```

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	factor.com
  Application Version:	0.0.0.0
  Application Timestamp:	55ddf79c
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	54504ade
  Exception Code:	e06d7363
  Exception Offset:	00014598
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	d893
  Additional Information 2:	d8930b777ff642ee4c44b35c0481e7b2
  Additional Information 3:	6758
  Additional Information 4:	6758e2431ad09c0029849a819cacb6f6
```

**Comment by erg** [comment]
Maybe these changes help/fix it? I can also give login info if ya'll want to take a look.

**Comment by erg** [comment]
Ok, patch seems good, no help on win32 crash (didnt expect it to).

**Comment by bjourne** [comment]
@mrjbq7 nope. It should work fine on previous vs:es too. I can't test it myself though. @erg I can take a look but I don't think it's related to this pr. There's probably a lot of features and changes introduced in vs2015.

**Comment by mrjbq7** [comment]
@erg want to test and merge I'm not at my windows VM.

**Comment by erg** [comment]
Merged. I opened issue #1461 for the win32 bootstrap crash.

**Pull request closed without merging**
