### PR TITLE
Rosetta Code Dice7 task implementation.

### PR DESCRIPTION
**Pull request by AlexIljin**

### CODE REVIEW

**Comment by erg** [comment]
Hi @AlexIljin, would it be possible to smash this down into a single commit? Thanks!

**Comment by AlexIljin** [comment]
Sure! Do you want me to do it, or were you asking my permission?

**Comment by AlexIljin** [comment]
@erg I'm not sure how notification system works on GitHub, but now I mentioned you, Doug, so you should receive updates. See my previous message.

**Comment by mrjbq7** [comment]
Either way, if its easy for you to make a squashed commit, otherwise I can.

**Comment by AlexIljin** [comment]
OK, how about this?

**Comment by mrjbq7** [comment]
Thanks, merged!

(I also made a few changes that @erg suggested in 07874dbb719423ed08691d0948dc5ae19dedcaeb).

**Pull request closed without merging**
