### PR TITLE
Fix 1265 and refactorings

### PR DESCRIPTION
**Pull request by bjourne**
Hello! This is an attempt to fix the #1265 bug which I've been working on for a while.

There was two bugs. One easy to fix. `code_block::scan` uses -1 most of the times as a sentinel value for "not found" but sometimes `f`. It crashed in `remove-breakpoints` because it assumes the `pos` argument is an integer. So now it always is.

The other one was really horrible. During a heap compaction, which runs in debug mode from `general_error`, all code blocks are packed in the beginning of the code heap. Then in `factor_vm::iterate_callstack` it calculated the wrong frame size because it didn't correctly adjust for that the code blocks have moved. 

Then when tracking these bugs down I've been trying to refactor the code to make it easier to understand. For example, I've changed a lot of variables types from `void*` to `cell` because that way you avoid lots of type casts back and forth. And many small functions where only used once and in those cases I think it's often better if the function where removed and its code inserted into the caller. Some other functions like `visit_code_roots` just called `visit_uninitialized_code_blocks` and nothing else. Then it's better to call `visit_uninitialized_code_blocks` directly and remove `visit_code_roots`.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Merged, thanks!!!

Works locally, lets see how the builders like it.

**Comment by mrjbq7** [comment]
Maybe a bug?  Builders failed with this:

```
}
Unit Test: {
    { }
    [ 10 [ [ minor-gc split-slice ] [ drop ] recover ] times ]
}
Loading resource:basis/compiler/tests/callback-error.factor
You have triggered a bug in Factor. Please report.
critical_error: Invalid header in size: 7feabcb808c0
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

> ==== DATA STACK:
[ [ ] [ "USING: alien alien.c-types alien.syntax kernel ;
    IN: scratchpad
    
    : callback-death ( -- callback )
        void { } cdecl [ "Error!" throw ] alien-callback ;
    
    : callback-invoke ( callback -- )
        void { } cdecl alien-indirect ;
    
    callback-death callback-invoke" compiler.tests.callback-error:callback-error-script io.encodings.ascii:ascii io.files:set-file-contents ] W{ tools.test.private:(unit-test) } 27 tools.test.private:experiment [ syntax:t ] [ compiler.tests.callback-error:run-vm-with-script ""Error!"" kernel:swap sequences:member? ] W{ tools.test.private:(unit-test) } 30 tools.test.private:experiment... ]
{ T{ compiler.tree:#call io.launcher:<process> T{ vectors:vector { } 0 } { 30405900 } f f f T{ hashtables:hashtable 1 0 { 30405900 T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } } T{ compiler.tree:#push [ system:vm make:, compiler.tests.callback-error:callback-error-script make:, ] { 30405901 } } T{ compiler.tree:#push { } { 30405902 } } T{ compiler.tree:#shuffle { { 30405903 30405902 } { 30405904 30405902 } } T{ vectors:vector { 30405902 } 1 } T{ vectors:vector { 30405903 30405904 } 2 } f f } T{ compiler.tree:#call sequences:sequence? T{ vectors:vector { 30405904 } 1 } { 30405905 } f f f T{ hashtables:hashtable 2 0 { 30405904 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:empty-interval { } syntax:t { T{ compiler.tree.propagation.info:value-info-state math:fixnum T{ math.intervals:interval { 0 syntax:t } { 0 syntax:t } } 0 syntax:t f } } } 30405905 T{ compiler.tree.propagation.info:value-info-state syntax:t math.intervals:empty-interval syntax:t syntax:t f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#if { 30405905 } { { T{ compiler.tree:#push [ 32 kernel:swap sequences:new-resizable [ make:building [ kernel:call ] namespaces:with-variable ] kernel:keep ] { 30405906 } } T{ compiler.tree:#shuffle { { 30405907 30405903 } { 30405908 30405906 } { 30405909 30405903 } } T{ vectors:vector { 30405903 30405906 } 2 } T{ vectors:vector { 30405907 30405908 30405909 } 3 } f f } T{ compiler.tree:#shuffle { { 30405910 30405909 } } T{ vectors:vector { 30405909 } 1 } f f T{ vectors:vector { 30405910 } 1 } } T{ compiler.tree:#shuffle { } { 30405908 } { } f f } T{ compiler.tree:#push 32 { 30405911 } } T{ compiler.tree:#shuffle { { 30405912 30405911 } { 30405913 30405907 } } T{ vectors:vector { 30405907 30405911 } 2 } T{ vectors:vector { 30405912 30405913 } 2 } f f } T{ compiler.tree:#call sequences:new-resizable T{ vectors:vector { 30405912 30405913 } 2 } { 30405914 } { T{ compiler.tree:#call sequence=>new-resizable T{ vectors:vector { 30405912 30405913 } 2 } { 30405914 } { T{ compiler.tree:#declare {  ...  } } T{ compiler.tree:#shuffle { } T{  ...   ...   ...  } T{  ...   ...   ...  } f f } T{ compiler.tree:#push 0 {  ...  } } T{ compiler.tree:#call arrays:<array> T{  ...   ...   ...  } {  ...  } f f f T{  ...   ...   ...   ...  } } T{ compiler.tree:#push 0 {  ...  } } T{ compiler.tree:#push vectors:vector {  ...  } } T{ compiler.tree:#shuffle { } T{  ...   ...   ...  } { } f f } T{ compiler.tree:#shuffle {  ...  } T{  ...   ...   ...  } f f T{  ...   ...   ...  } } T{ compiler.tree:#shuffle {  ...   ...  } T{  ...   ...   ...  } T{  ...   ...   ...  } f f } T{ compiler.tree:#call arrays:array? T{  ...   ...   ...  } {  ...  } f f f T{  ...   ...   ...   ...  } }... } f f T{ hashtables:hashtable 3 0 { 30405912 T{  ...   ...   ...   ...   ...   ...  } 30405913 T{  ...   ...   ...   ...   ...   ...  } 30405914 T{  ...   ...   ...   ...   ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  }... } } } } sequence=>new-resizable arrays:array T{ hashtables:hashtable 3 0 { 30405912 T{ compiler.tree.propagation.info:value-info-state math:fixnum T{ math.intervals:interval {  ...   ...  } {  ...   ...  } } 32 syntax:t f } 30405913 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:empty-interval { } syntax:t { T{  ...   ...   ...   ...   ...   ...  } } } 30405914 T{ compiler.tree.propagation.info:value-info-state vectors:vector math.intervals:full-interval f f T{ vectors:vector {  ...   ...   ...  } 3 } } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#push [ make:building [ kernel:call ] namespaces:with-variable ] { 30405915 } } T{ compiler.tree:#shuffle { { 30405916 30405914 } { 30405917 30405915 } { 30405918 30405914 } } T{ vectors:vector { 30405914 30405915 } 2 } T{ vectors:vector { 30405916 30405917 30405918 } 3 } f f } T{ compiler.tree:#shuffle { { 30405919 30405918 } } T{ vectors:vector { 30405918 } 1 } f f T{ vectors:vector { 30405919 } 1 } }... } { T{ compiler.tree:#push 5 { 30406044 } } T{ compiler.tree:#shuffle { { 30406045 30406044 } { 30406046 30405903 } } T{ vectors:vector { 30405903 30406044 } 2 } T{ vectors:vector { 30406045 30406046 } 2 } f f } T{ compiler.tree:#call assocs:new-assoc T{ vectors:vector { 30406045 30406046 } 2 } { 30406047 } f f f f } T{ compiler.tree:#push [ make:building [ kernel:call ] namespaces:with-variable ] { 30406048 } } T{ compiler.tree:#shuffle { { 30406049 30406047 } { 30406050 30406048 } { 30406051 30406047 } } T{ vectors:vector { 30406047 30406048 } 2 } T{ vectors:vector { 30406049 30406050 30406051 } 3 } f f } T{ compiler.tree:#shuffle { { 30406052 30406051 } } T{ vectors:vector { 30406051 } 1 } f f T{ vectors:vector { 30406052 } 1 } } T{ compiler.tree:#shuffle { } { 30406050 } { } f f } T{ compiler.tree:#push make:building { 30406053 } } T{ compiler.tree:#push [ kernel:call ] { 30406054 } } T{ compiler.tree:#shuffle { { 30406055 30406054 } } T{ vectors:vector { 30406054 } 1 } f f T{ vectors:vector { 30406055 } 1 } }... } } { syntax:t f } } T{ compiler.tree:#phi { { 30406029 30406043 } { 30406162 30406174 } } { { T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:full-interval f f f } } { T{ compiler.tree.propagation.info:value-info-state kernel:null math.intervals:empty-interval f f f } T{ compiler.tree.propagation.info:value-info-state kernel:null math.intervals:empty-interval f f f } } } { 30406175 30406176 } T{ vectors:vector { f f } 2 } } T{ compiler.tree:#shuffle { { 30406177 30406175 } { 30406178 30406176 } { 30406179 30406175 } } T{ vectors:vector { 30406175 30406176 } 2 } T{ vectors:vector { 30406177 30406178 30406179 } 3 } f f } T{ compiler.tree:#call accessors:command<< T{ vectors:vector { 30406178 30406179 } 2 } { } f f f T{ hashtables:hashtable 2 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } 30406178 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:full-interval f f f } 30406179 T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#push io.launcher:+closed+ { 30406180 } }... }
T{ compiler.tree:#call kernel:compose T{ vectors:vector { 30406202 30406203 } 2 } { 30406213 } f f f f }
kernel:compose
30406543
quotations:callable
==== RETAIN STACK:
6244860461939072
{ "24-game" "99-bottles" "accessors" "alien" "alien.accessors" "alien.arrays" "alien.c-types" "alien.c-types.private" "alien.complex" "alien.complex.functor"... }
2789
411
{ "resource:basis/compiler/tests/redefine20.factor" "resource:basis/compiler/tests/alien.factor" "resource:basis/compiler/tests/redefine1.factor" "resource:basis/compiler/tests/simple.factor" "resource:basis/compiler/tests/low-level-ir.factor" "resource:basis/compiler/tests/redefine15.factor" "resource:basis/compiler/tests/redefine16.factor" "resource:basis/compiler/tests/redefine9.factor" "resource:basis/compiler/tests/redefine26.factor" "resource:basis/compiler/tests/redefine22.factor"... }
{ "resource:basis/compiler/tests/redefine20.factor" "resource:basis/compiler/tests/alien.factor" "resource:basis/compiler/tests/redefine1.factor" "resource:basis/compiler/tests/simple.factor" "resource:basis/compiler/tests/low-level-ir.factor" "resource:basis/compiler/tests/redefine15.factor" "resource:basis/compiler/tests/redefine16.factor" "resource:basis/compiler/tests/redefine9.factor" "resource:basis/compiler/tests/redefine26.factor" "resource:basis/compiler/tests/redefine22.factor"... }
49
14
{ compiler.tests.callback-error:callback-error-script compiler.tests.callback-error:run-vm-with-script }
{ compiler.tests.callback-error:callback-error-script compiler.tests.callback-error:run-vm-with-script }
2
1
compiler.tests.callback-error:run-vm-with-script
compiler.tests.callback-error:run-vm-with-script
{ T{ compiler.tree:#call io.launcher:<process> T{ vectors:vector { } 0 } { 30405900 } f f f T{ hashtables:hashtable 1 0 { 30405900 T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } } T{ compiler.tree:#push [ system:vm make:, compiler.tests.callback-error:callback-error-script make:, ] { 30405901 } } T{ compiler.tree:#push { } { 30405902 } } T{ compiler.tree:#shuffle { { 30405903 30405902 } { 30405904 30405902 } } T{ vectors:vector { 30405902 } 1 } T{ vectors:vector { 30405903 30405904 } 2 } f f } T{ compiler.tree:#call sequences:sequence? T{ vectors:vector { 30405904 } 1 } { 30405905 } f f f T{ hashtables:hashtable 2 0 { 30405904 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:empty-interval { } syntax:t { T{ compiler.tree.propagation.info:value-info-state math:fixnum T{ math.intervals:interval { 0 syntax:t } { 0 syntax:t } } 0 syntax:t f } } } 30405905 T{ compiler.tree.propagation.info:value-info-state syntax:t math.intervals:empty-interval syntax:t syntax:t f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#if { 30405905 } { { T{ compiler.tree:#push [ 32 kernel:swap sequences:new-resizable [ make:building [ kernel:call ] namespaces:with-variable ] kernel:keep ] { 30405906 } } T{ compiler.tree:#shuffle { { 30405907 30405903 } { 30405908 30405906 } { 30405909 30405903 } } T{ vectors:vector { 30405903 30405906 } 2 } T{ vectors:vector { 30405907 30405908 30405909 } 3 } f f } T{ compiler.tree:#shuffle { { 30405910 30405909 } } T{ vectors:vector { 30405909 } 1 } f f T{ vectors:vector { 30405910 } 1 } } T{ compiler.tree:#shuffle { } { 30405908 } { } f f } T{ compiler.tree:#push 32 { 30405911 } } T{ compiler.tree:#shuffle { { 30405912 30405911 } { 30405913 30405907 } } T{ vectors:vector { 30405907 30405911 } 2 } T{ vectors:vector { 30405912 30405913 } 2 } f f } T{ compiler.tree:#call sequences:new-resizable T{ vectors:vector { 30405912 30405913 } 2 } { 30405914 } { T{ compiler.tree:#call sequence=>new-resizable T{ vectors:vector { 30405912 30405913 } 2 } { 30405914 } { T{ compiler.tree:#declare {  ...  } } T{ compiler.tree:#shuffle { } T{  ...   ...   ...  } T{  ...   ...   ...  } f f } T{ compiler.tree:#push 0 {  ...  } } T{ compiler.tree:#call arrays:<array> T{  ...   ...   ...  } {  ...  } f f f T{  ...   ...   ...   ...  } } T{ compiler.tree:#push 0 {  ...  } } T{ compiler.tree:#push vectors:vector {  ...  } } T{ compiler.tree:#shuffle { } T{  ...   ...   ...  } { } f f } T{ compiler.tree:#shuffle {  ...  } T{  ...   ...   ...  } f f T{  ...   ...   ...  } } T{ compiler.tree:#shuffle {  ...   ...  } T{  ...   ...   ...  } T{  ...   ...   ...  } f f } T{ compiler.tree:#call arrays:array? T{  ...   ...   ...  } {  ...  } f f f T{  ...   ...   ...   ...  } }... } f f T{ hashtables:hashtable 3 0 { 30405912 T{  ...   ...   ...   ...   ...   ...  } 30405913 T{  ...   ...   ...   ...   ...   ...  } 30405914 T{  ...   ...   ...   ...   ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  }... } } } } sequence=>new-resizable arrays:array T{ hashtables:hashtable 3 0 { 30405912 T{ compiler.tree.propagation.info:value-info-state math:fixnum T{ math.intervals:interval {  ...   ...  } {  ...   ...  } } 32 syntax:t f } 30405913 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:empty-interval { } syntax:t { T{  ...   ...   ...   ...   ...   ...  } } } 30405914 T{ compiler.tree.propagation.info:value-info-state vectors:vector math.intervals:full-interval f f T{ vectors:vector {  ...   ...   ...  } 3 } } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#push [ make:building [ kernel:call ] namespaces:with-variable ] { 30405915 } } T{ compiler.tree:#shuffle { { 30405916 30405914 } { 30405917 30405915 } { 30405918 30405914 } } T{ vectors:vector { 30405914 30405915 } 2 } T{ vectors:vector { 30405916 30405917 30405918 } 3 } f f } T{ compiler.tree:#shuffle { { 30405919 30405918 } } T{ vectors:vector { 30405918 } 1 } f f T{ vectors:vector { 30405919 } 1 } }... } { T{ compiler.tree:#push 5 { 30406044 } } T{ compiler.tree:#shuffle { { 30406045 30406044 } { 30406046 30405903 } } T{ vectors:vector { 30405903 30406044 } 2 } T{ vectors:vector { 30406045 30406046 } 2 } f f } T{ compiler.tree:#call assocs:new-assoc T{ vectors:vector { 30406045 30406046 } 2 } { 30406047 } f f f f } T{ compiler.tree:#push [ make:building [ kernel:call ] namespaces:with-variable ] { 30406048 } } T{ compiler.tree:#shuffle { { 30406049 30406047 } { 30406050 30406048 } { 30406051 30406047 } } T{ vectors:vector { 30406047 30406048 } 2 } T{ vectors:vector { 30406049 30406050 30406051 } 3 } f f } T{ compiler.tree:#shuffle { { 30406052 30406051 } } T{ vectors:vector { 30406051 } 1 } f f T{ vectors:vector { 30406052 } 1 } } T{ compiler.tree:#shuffle { } { 30406050 } { } f f } T{ compiler.tree:#push make:building { 30406053 } } T{ compiler.tree:#push [ kernel:call ] { 30406054 } } T{ compiler.tree:#shuffle { { 30406055 30406054 } } T{ vectors:vector { 30406054 } 1 } f f T{ vectors:vector { 30406055 } 1 } }... } } { syntax:t f } } T{ compiler.tree:#phi { { 30406029 30406043 } { 30406162 30406174 } } { { T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:full-interval f f f } } { T{ compiler.tree.propagation.info:value-info-state kernel:null math.intervals:empty-interval f f f } T{ compiler.tree.propagation.info:value-info-state kernel:null math.intervals:empty-interval f f f } } } { 30406175 30406176 } T{ vectors:vector { f f } 2 } } T{ compiler.tree:#shuffle { { 30406177 30406175 } { 30406178 30406176 } { 30406179 30406175 } } T{ vectors:vector { 30406175 30406176 } 2 } T{ vectors:vector { 30406177 30406178 30406179 } 3 } f f } T{ compiler.tree:#call accessors:command<< T{ vectors:vector { 30406178 30406179 } 2 } { } f f f T{ hashtables:hashtable 2 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } 30406178 T{ compiler.tree.propagation.info:value-info-state arrays:array math.intervals:full-interval f f f } 30406179 T{ compiler.tree.propagation.info:value-info-state kernel:object math.intervals:full-interval f f f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } } T{ compiler.tree:#push io.launcher:+closed+ { 30406180 } }... }
66
34
T{ compiler.tree:#call kernel:compose T{ vectors:vector { 30406202 30406203 } 2 } { 30406213 } f f f f }
T{ compiler.tree:#call kernel:compose T{ vectors:vector { 30406202 30406203 } 2 } { 30406213 } f f f f }
kernel:compose
{ 30406213 }
kernel:compose
f
[ [ kernel:dup quotations:callable? T{ kernel:curry quotations:callable [ slots:bad-slot-value ] } kernel:unless ] kernel:dip kernel:dup quotations:callable? T{ kernel:curry quotations:callable [ slots:bad-slot-value ] } kernel:unless { kernel:compose 2 1 kernel:tuple 258304024774 kernel:compose 366639970744 } classes.tuple.private:<tuple-boa> ]
8
5
T{ stack-checker.recursive-state:recursive-state f f }
T{ vectors:vector { 0 0 0 0 0 0 } 0 }
[ kernel:swap [ kernel:drop ] [ kernel:call ] kernel:if ]
4
3
T{ vectors:vector { [ kernel:drop ] [ kernel:call ] } 2 }
T{ vectors:vector { T{ hashtables:hashtable 10 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } f } 2 }
T{ vectors:vector { [ kernel:drop ] [ kernel:call ] } 2 }
T{ vectors:vector { T{ hashtables:hashtable 10 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } f } 2 }
2
1
T{ vectors:vector { T{ hashtables:hashtable 10 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } f } 2 }
1
T{ vectors:vector { } 0 }
[ kernel:call ]
1
0
2
2
0
T{ stack-checker.values:declared-effect T{ stack-checker.values:literal-tuple T{ kernel:curry quotations:callable [ slots:bad-slot-value ] } T{ stack-checker.recursive-state:recursive-state f f } } kernel:unless T{ effects:effect { } { } f "a" "a" } T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } T{ vectors:vector { T{ stack-checker.values:declared-effect T{ stack-checker.values:literal-tuple T{ kernel:curry quotations:callable [ slots:bad-slot-value ] } T{ stack-checker.recursive-state:recursive-state f f } } kernel:unless T{ effects:effect { } { } f "a" "a" } T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } T{ vectors:vector { T{ stack-checker.values:declared-effect T{ stack-checker.values:literal-tuple T{ kernel:curry quotations:callable [  ...  ] } T{ stack-checker.recursive-state:recursive-state f f } } kernel:unless T{ effects:effect { } { } f "a" "a" } T{ hashtables:hashtable 0 0 { T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } T{  ...   ...  } } } T{ vectors:vector { T{  ...   ...   ...   ...   ...   ...   ...  } 0 0 } 1 } f } 0 0 } 1 } f } 0 0 } 1 } f }
T{ stack-checker.recursive-state:recursive-state f T{ stack-checker.recursive-state.tree:node kernel:unless kernel:unless 262639375044 f f } }
T{ vectors:vector { } 0 }
T{ kernel:curry quotations:callable [ slots:bad-slot-value ] }
2
0
==== CALL STACK:

frame: 0x7feaf7b3ad58 size 32
executing: memory:minor-gc
scan: 1
word/quot addr: 7fea91ce311c
word/quot xt: 7feadd520820
return address: 7feadd520851

frame: 0x7feaf7b3ad78 size 16
executing: word=>literalize
scan: -1
word/quot addr: 7fea8bbb0a5c
word/quot xt: 7feadd5369e0
return address: 7feadd536a18

frame: 0x7feaf7b3ad88 size 16
executing: stack-checker.backend:infer-quot-here
scan: -1
word/quot addr: 7fea8be3cc6c
word/quot xt: 7feadd0be8c0
return address: 7feadd0be9e8

frame: 0x7feaf7b3ad98 size 16
executing: stack-checker.backend:infer-quot
scan: -1
word/quot addr: 7fea8fea52dc
word/quot xt: 7feadd55d6f0
return address: 7feadd55d73d

frame: 0x7feaf7b3ada8 size 32
executing: declared-effect=>infer-call*
scan: -1
word/quot addr: 7fea90e9246c
word/quot xt: 7feadd2a9b50
return address: 7feadd2a9bfb

frame: 0x7feaf7b3adc8 size 16
executing: stack-checker.backend:infer-quot-here
scan: -1
word/quot addr: 7fea8be3cc6c
word/quot xt: 7feadd0be8c0
return address: 7feadd0be9ed

frame: 0x7feaf7b3add8 size 16
executing: callable=>infer-branch
scan: -1
word/quot addr: 7fea9025c37c
word/quot xt: 7feadd1ea010
return address: 7feadd1ea0e3

frame: 0x7feaf7b3ade8 size 16
executing: stack-checker.branches:(infer-if)
scan: -1
word/quot addr: 7fea8fe62eac
word/quot xt: 7feadd46a8a0
return address: 7feadd46a996

frame: 0x7feaf7b3adf8 size 16
executing: stack-checker.backend:infer-quot-here
scan: -1
word/quot addr: 7fea8be3cc6c
word/quot xt: 7feadd0be8c0
return address: 7feadd0be9ed

frame: 0x7feaf7b3ae08 size 16
executing: stack-checker.backend:infer-quot
scan: -1
word/quot addr: 7fea8fea52dc
word/quot xt: 7feadd55d6f0
return address: 7feadd55d73d

frame: 0x7feaf7b3ae18 size 16
executing: stack-checker.backend:infer-quot-here
scan: -1
word/quot addr: 7fea8be3cc6c
word/quot xt: 7feadd0be8c0
return address: 7feadd0be9ed

frame: 0x7feaf7b3ae28 size 16
executing: word=>(build-tree)
scan: -1
word/quot addr: 7fea906f33ac
word/quot xt: 7feadd487c70
return address: 7feadd487c9d

frame: 0x7feaf7b3ae38 size 16
executing: compiler.tree.builder.private:build-tree-with
scan: -1
word/quot addr: 7fea9000237c
word/quot xt: 7feadd0411f0
return address: 7feadd04141a

frame: 0x7feaf7b3ae48 size 16
executing: compiler.tree.builder:build-sub-tree
scan: -1
word/quot addr: 7fea9017b70c
word/quot xt: 7feadd49ff30
return address: 7feadd4a00f6

frame: 0x7feaf7b3ae58 size 16
executing: compiler.tree.propagation.inlining:splicing-body
scan: -1
word/quot addr: 7fea900d1acc
word/quot xt: 7feadd29ee00
return address: 7feadd29ee0f

frame: 0x7feaf7b3ae68 size 16
executing: compiler.tree.propagation.inlining:inline-word
scan: -1
word/quot addr: 7fea8ff6447c
word/quot xt: 7feadce65b90
return address: 7feadce65c03

frame: 0x7feaf7b3ae78 size 16
executing: compiler.tree.propagation.inlining:do-inlining
scan: -1
word/quot addr: 7fea8ffe1fdc
word/quot xt: 7feadd4cb5d0
return address: 7feadd4cb6f7

frame: 0x7feaf7b3ae88 size 16
executing: #call=>propagate-before
scan: -1
word/quot addr: 7fea906e4e9c
word/quot xt: 7feadd19bdf0
return address: 7feadd19be56

frame: 0x7feaf7b3ae98 size 16
executing: node=>propagate-around
scan: -1
word/quot addr: 7fea906d346c
word/quot xt: 7feadd4dce50
return address: 7feadd4dce69

frame: 0x7feaf7b3aea8 size 16
executing: compiler.tree.propagation.nodes:(propagate)
scan: -1
word/quot addr: 7fea8ff402ec
word/quot xt: 7feadd1c8a30
return address: 7feadd1c8aea

frame: 0x7feaf7b3aeb8 size 16
executing: compiler.tree.optimizer:optimize-tree
scan: -1
word/quot addr: 7fea901aa00c
word/quot xt: 7feadd4cb8b0
return address: 7feadd4cb953

frame: 0x7feaf7b3aec8 size 16
executing: compiler:frontend
scan: -1
word/quot addr: 7fea8ff6267c
word/quot xt: 7feadd044e30
return address: 7feadd044fd7

frame: 0x7feaf7b3aed8 size 16
executing: compiler:compile-word
scan: -1
word/quot addr: 7fea8d45e2ec
word/quot xt: 7feadd2feea0
return address: 7feadd2fefa6

frame: 0x7feaf7b3aee8 size 16
executing: optimizing-compiler=>recompile
scan: -1
word/quot addr: 7fea8d45e38c
word/quot xt: 7feadd4eed90
return address: 7feadd4ef1ce

frame: 0x7feaf7b3aef8 size 16
executing: compiler.units.private:finish-compilation-unit
scan: -1
word/quot addr: 7fea8d43ddac
word/quot xt: 7feadd4ef940
return address: 7feadd4ef9a2

frame: 0x7feaf7b3af08 size 16
executing: parser:parse-stream
scan: -1
word/quot addr: 7fea8e1df9ac
word/quot xt: 7feadd5245c0
return address: 7feadd5254a2

frame: 0x7feaf7b3af18 size 16
executing: parser:parse-file
scan: -1
word/quot addr: 7fea8e1dfa4c
word/quot xt: 7feadcece4c0
return address: 7feadcece70c

frame: 0x7feaf7b3af28 size 16
executing: parser:run-file
scan: -1
word/quot addr: 7fea8e1dd9dc
word/quot xt: 7feadd5268c0
return address: 7feadd5268cf

frame: 0x7feaf7b3af38 size 16
executing: tools.test:run-test-file
scan: -1
word/quot addr: 7fea8eef5cac
word/quot xt: 7feadda761f0
return address: 7feadda764ac

frame: 0x7feaf7b3af48 size 16
executing: tools.test.private:test-vocab
scan: -1
word/quot addr: 7fea8eef5e8c
word/quot xt: 7feadda22900
return address: 7feadda229d5

frame: 0x7feaf7b3af58 size 16
executing: tools.test.private:test-vocabs
scan: -1
word/quot addr: 7fea8eef5edc
word/quot xt: 7feadda758a0
return address: 7feadda7593c

frame: 0x7feaf7b3af68 size 16
executing: mason.test:do-tests
scan: -1
word/quot addr: 7fea8ee959fc
word/quot xt: 7feaddcb5a50
return address: 7feaddcb5a83

frame: 0x7feaf7b3af78 size 16
executing: mason.test:do-all
scan: -1
word/quot addr: 7fea8ee95bdc
word/quot xt: 7feaddcc1c80
return address: 7feaddcc2042

frame: 0x7feaf7b3af88 size 16
executing: command-line.startup:command-line-startup
scan: -1
word/quot addr: 7fea9025b5bc
word/quot xt: 7feaddc7cb50
return address: 7feaddc7d8f0

frame: 0x7feaf7b3af98 size 32
executing: [ [ continuations.private:catchstack* sequences:push ] kernel:dip kernel:call continuations.private:catchstack* sequences:pop* ]
scan: 2
word/quot addr: 7fea8c627ff4
word/quot xt: 7feadcf173e0
return address: 7feadcf17410

frame: 0x7feaf7b3afb8 size 32
executing: kernel.private:c-to-factor
scan: 1
word/quot addr: 7fea8bb4037c
word/quot xt: 7feadd3669a0
return address: 7feadd3669c4
Launcher error:
Process exited with error code 1

Launch descriptor:

T{ process
    { command { "./factor" "-run=mason.test" } }
    { environment H{ } }
    { environment-mode +append-environment+ }
    { stdin +closed+ }
    { stdout "../test-log" }
    { stderr +stdout+ }
    { group +new-group+ }
    { timeout T{ duration { hour 4 } } }
    { status 1 }
}
```

**Comment by erg** [comment]
I checked this, they have been failing with that since last patches too.

On Thu, Jan 15, 2015 at 7:45 AM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment]
oh weird, when did they start failing?

**Comment by erg** [comment]
Dec 30th. We probably pulled all these at the same time. I think it's not a
new bug, just that we finally have a unit test that exposes it. Sadly,
@bjourne's new fix isn't enough for this bug but he fixed something else.

GC is hard, let's write b-trees! jk jk jk

minor-gc unit test patch:
https://github.com/slavapestov/factor/commit/79d294e4bf4cbfeaa05b47fdeed79f176951c11c


first failing build:
https://github.com/slavapestov/factor/commit/d0dde922bd87f5c69abfcf7326619d016a650a92


On Thu, Jan 15, 2015 at 7:46 AM, John Benediktsson <notifications@github.com

**Comment by bjourne** [comment]
Yeah, the split-slice thingy is old I think. I had added that test locally and then it accidentally got into a commit which it probably shouldn't have.

**Pull request merged**
