### PR TITLE
primitives: Change PRIMITIVE: to check that the word is in that vocab…

### PR DESCRIPTION
**Pull request by erg**
…ulary and the stack effect is correct.

Use PRIMITIVE: in core/ and basis/

### CODE REVIEW

**Comment by mrjbq7** [comment]
It's cool for grep but weird because it doesn't actually do anything.

**Comment by erg** [comment]
It's good for new parser so you can make the namespace from tokens that you actually parse instead of magic.

**Comment by mrjbq7** [comment]
Is there anyway to make it replace the define-primitive in bootstrap?

**Comment by erg** [comment]
Maybe in another patch?

**Comment by mrjbq7** [comment]
If it's not technically possible this is just for documentation or does the new parser require it?

**Comment by mrjbq7** [comment]
I'm not even super happy with BUILTIN

**Comment by erg** [comment]
The reason for it is to put a symbol in the vocabulary so when the parser makes a symbol table from things it parsed there can be an entry. Same thing for builtin.

**Comment by erg** [comment]
Only accessors and predicates don't have a symbol in src after this?

**Comment by mrjbq7** [comment]
I'm not sure I agree that everything needs a grepable symbol - I mean we have dynamic symbol tables for a reason, no?

**Comment by mrjbq7** [comment]
It would be cool if PRIMITIVE actually defined it the way define-primitive works, no?

**Comment by mrjbq7** [comment]
Or maybe ``make-sub-primitive`` and ``make-primitive``?

**Comment by mrjbq7** [comment]
I suppose, since you are making ``PRIMITIVE:`` work like ``BUILTIN:`` which just scans and checks the word is a primitive, this is probably okay.

**Comment by mrjbq7** [comment]
But long term we should fix bootstrapping to maybe use the syntax better.

**Comment by erg** [comment]
We have to undo all the dumb stuff the current parser does piece by piece.

**Comment by mrjbq7** [comment]
Okay, well +1.

Does this have all the primitives or sub primitives from bootstrap.primitives?

**Comment by erg** [comment]
All 224 as per all-words [ primitive? ] filter

**Comment by jonenst** [comment]
> Only accessors and predicates don't have a symbol in src after this?

Not sure if that's what you meant, but there are still many places where we use create-word-in, and FUNCTOR:
```
git grep create-word-in
basis/alien/enums/enums.factor:    [ name>> "<" ">" surround create-word-in ] keep
basis/alien/parser/parser.factor:    create-word-in dup reset-generic ;
basis/alien/parser/parser.factor:    [ nip name>> "set-" prepend create-word-in ]
basis/compiler/cfg/hats/hats.factor:    name>> "##" ?head drop "^^" prepend create-word-in ;
basis/compiler/cfg/instructions/syntax/syntax.factor:    [ [ insn-ctor-name create-word-in ] [ '[ _ ] [ f ] [ boa , ] surround ] bi ] dip
basis/cpu/x86/assembler/syntax/syntax.factor:    [ create-word-in ] 2dip {
basis/functors/functors.factor:SYNTAX: DEFINES [ create-word-in ] (INTERPOLATE) ;
basis/functors/functors.factor:SYNTAX: DEFINES-PRIVATE [ begin-private create-word-in end-private ] (INTERPOLATE) ;
basis/gobject-introspection/ffi/ffi.factor:!     create-word-in dup
basis/gobject-introspection/standard-types/standard-types.factor:"gboolean" create-word-in typedef
basis/gobject-introspection/types/types.factor:"deferred-type" create-word-in typedef
basis/io/encodings/8-bit/8-bit.factor:    create-word-in
basis/match/match.factor:    create-word-in
basis/math/vectors/simd/cords/cords.factor:    [ create-word-in (define-simd-128-cord) ] 2bi ;
basis/openssl/libssl/libssl.factor:    scan-token "X509_V_" prepend create-word-in
basis/roman/roman.factor:    scan-word [ name>> "roman" prepend create-word-in ] keep
basis/tools/test/test.factor:    [ create-word-in ]
basis/tr/tr.factor:    create-word-in dup tr-hints ;
basis/unicode/breaks/breaks.factor:"grapheme-table" create-word-in
basis/unicode/breaks/breaks.factor:"word-break-table" create-word-in
basis/unicode/breaks/breaks.factor:"word-table" create-word-in
basis/unicode/script/script.factor:"script-table" create-word-in
basis/windows/com/syntax/syntax.factor:    word>> name>> "-iid" append create-word-in ;
basis/windows/com/syntax/syntax.factor:    3append create-word-in ;
basis/xmode/tokens/tokens.factor:    dup create-word-in dup define-symbol
core/parser/parser-docs.factor:HELP: create-word-in
core/parser/parser.factor:: create-word-in ( str -- word )
core/parser/parser.factor:    ] [ create-word-in ] if ;
core/parser/parser.factor:    scan-word-name create-word-in ;
core/syntax/syntax.factor:        ";" [ create-word-in [ reset-generic ] [ define-symbol ] bi ] each-token
core/words/words-docs.factor:    create-word-in
core/words/words-docs.factor:{ $notes "This word must be called from inside " { $link with-compilation-unit } ". Parsing words should call " { $link create-word-in } " instead of this word." } ;
extra/constructors/constructors.factor:    create-word-in dup reset-generic ;
extra/cpu/8080/emulator/emulator.factor:       "_" join [ "emulate-" % % ] "" make create-word-in
extra/cuda/syntax/syntax.factor:    scan-token [ create-word-in current-cuda-library get ] keep
extra/cuda/syntax/syntax.factor:    scan-token [ create-word-in current-cuda-library get ] keep
extra/game/worlds/worlds.factor:    [ name>> "-attributes" append create-word-in ] dip define-constant ;
extra/gml/macros/macros.factor:        name "-record" append create-word-in :> record-class
extra/gml/runtime/runtime.factor:    scan-token [ "gml-" prepend create-word-in ] keep ;
extra/project-euler/common/common.factor:    [ name>> "-main" append create-word-in ] keep
extra/python/syntax/syntax.factor:    [ create-word-in ] bi@ ;
extra/python/syntax/syntax.factor:    [ dup create-word-in swap ] dip [ make-method-quot ] keep define-inline ;
extra/python/syntax/syntax.factor:    [ "$" prepend create-word-in ] [ '[ _ getattr ] ] bi
extra/variants/variants.factor:    dup name>> "<" ">" surround create-word-in swap define-boa-word ;
unmaintained/alien/cxx/cxx.factor:    "#" append create-word-in ;
unmaintained/alien/marshall/structs/structs.factor:        [ name>> "<" prepend ">" append create-word-in ]
unmaintained/alien/marshall/structs/structs.factor:    name create-word-in :> class
unmaintained/modules/rpc/rpc.factor:    str create-word-in effect [ in>> length ] [ out>> length ] bi
unmaintained/semantic-db/semantic-db.factor:    >r create-word-in over [ execute ] curry r> compose define ;
unmaintained/semantic-db/semantic-db.factor:    dup id-word>> "id-word" choose-word-name create-word-in ;

git grep FUNCTOR:
basis/alien/complex/functor/functor.factor:FUNCTOR: define-complex-type ( N T -- )
basis/alien/destructors/destructors.factor:FUNCTOR: define-destructor ( F -- )
basis/compiler/cfg/dataflow-analysis/dataflow-analysis.factor:FUNCTOR: define-analysis ( name -- )
basis/compiler/cfg/dataflow-analysis/dataflow-analysis.factor:FUNCTOR: define-forward-analysis ( name -- )
basis/compiler/cfg/dataflow-analysis/dataflow-analysis.factor:FUNCTOR: define-backward-analysis ( name -- )
basis/compiler/cfg/renaming/functor/functor.factor:FUNCTOR: define-renaming ( NAME DEF-QUOT USE-QUOT TEMP-QUOT -- )
basis/functors/functors-tests.factor:FUNCTOR: define-box ( T -- )
basis/functors/functors-tests.factor:FUNCTOR: wrapper-test ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: wrapper-test-2 ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: symbol-test ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: generic-test ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: redefine-test ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: define-a-struct ( T NAME TYPE N -- )
basis/functors/functors-tests.factor:FUNCTOR: define-an-inline-word ( W -- )
basis/functors/functors-tests.factor:FUNCTOR: define-a-final-class ( T W -- )
basis/functors/functors.factor:: (FUNCTOR:) ( -- word def effect )
basis/functors/functors.factor:SYNTAX: FUNCTOR: (FUNCTOR:) define-declared ;
basis/math/vectors/simd/cords/cords.factor:FUNCTOR: (define-simd-128-cord) ( A/2 A -- )
basis/math/vectors/simd/simd.factor:FUNCTOR: define-simd-128 ( T -- )
basis/sequences/cords/cords.factor:FUNCTOR: define-specialized-cord ( T C -- )
basis/sorting/functor/functor.factor:FUNCTOR: define-sorting ( NAME QUOT -- )
basis/specialized-arrays/specialized-arrays.factor:FUNCTOR: define-array ( T -- )
basis/specialized-vectors/specialized-vectors.factor:FUNCTOR: define-vector ( T -- )
basis/tuple-arrays/tuple-arrays.factor:FUNCTOR: define-tuple-array ( CLASS -- )
basis/ui/pixel-formats/pixel-formats.factor:FUNCTOR: define-pixel-format-attribute-table ( NAME PERM TABLE -- )
basis/vectors/functor/functor.factor:FUNCTOR: define-vector ( V A <A> -- )
extra/annotations/annotations.factor:FUNCTOR: define-annotation ( NAME -- )
extra/classes/struct/vectored/vectored.factor:FUNCTOR: define-vectored-accessors ( S>> S<< T -- )
extra/classes/struct/vectored/vectored.factor:FUNCTOR: define-vectored-struct ( T -- )
extra/math/blas/matrices/matrices.factor:FUNCTOR: (define-blas-matrix) ( TYPE T U C -- )
extra/math/blas/vectors/vectors.factor:FUNCTOR: (define-blas-vector) ( TYPE T -- )
extra/math/blas/vectors/vectors.factor:FUNCTOR: (define-real-blas-vector) ( TYPE T -- )
extra/math/blas/vectors/vectors.factor:FUNCTOR: (define-complex-blas-vector) ( TYPE C S -- )
extra/tc-lisp-talk/tc-lisp-talk.factor:            """FUNCTOR: define-sorting ( NAME QUOT -- )
extra/tokyo/assoc-functor/assoc-functor.factor:FUNCTOR: define-tokyo-assoc-api ( T N -- )
misc/Factor.tmbundle/Snippets/functor.tmSnippet:FUNCTOR: $1 ( $2 -- $3 )
unmaintained/alien/marshall/private/private.factor:FUNCTOR: define-primitive-marshallers ( TYPE -- )
unmaintained/models/combinators/templates/templates.factor:FUNCTOR: fmaps ( W -- )
```

**Pull request merged**
