### PR TITLE
Windows fixes part3

### PR DESCRIPTION
**Pull request by bjourne**
Here is another VM refactoring branch. It removes the `RT_EXCEPTION_HANDLER` relocation type which was only used on Windows and replaces it with a special object. Then it changes the ffi to not look for decorated symbols on win32. It makes the code for loading ffi functions a bit simpler. Guess I can try committing this myself? :) The boot images will need to be updated.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Looks good to me (haven't tested it but if it works locally for you let the build bots have a go!)

Do you know how to upload new boot images?

```
./factor -run=bootstrap.image.upload
```

I will send you password separately.

**Comment by mrjbq7** [comment]
Yay!!

**Comment by bjourne** [comment]
Hm it crashes. I'll try uploading that boot image.

**Comment by mrjbq7** [comment]
Looks like some bootstrap.image test failures.  Also, for some reason formatting tests fail on Windows.  There's a difference between the number of exponent characters and I can't remember right now where that was fixed up, so maybe not caused by you?

**Comment by erg** [comment]
Vs 2013 has the buggy formatting. I restarted with vs2015.

**Comment by bjourne** [comment]
I see the bootstrap.image failure. I'll try and push a fix.

**Pull request merged**
