### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by bpollack**
More coming, but these were quick for me to get done, and gaps I hit today.

### CODE REVIEW

**Comment by mrjbq7** [comment]
Do you want us to merge these, or just keep adding to this pull request?

**Comment by bpollack** [comment]
I don't really care, to be honest; if you sit on the PR for a bit, I'll keep adding to it (and optionally squash them when I'm done), and if you merge them, I'll just open a new one as I continue work.  As long as the docs look good to you, I'll keep working on this.

**Comment by bpollack** [comment]
@mrjbq7 You can merge at this point; I'm not going to have more time to work on this until Monday, and this seems like a meaningful step forward.

**Comment by mrjbq7** [comment]
Merged, thanks!!

(Fixed some minor errors that ``help-lint`` warned about in ac23acc2c98e7a897a5d12f3bebe283174c36a6c).

**Pull request closed without merging**
